### ISSUE TITLE
Adding a link to `jbeam_edit` (JBeam tool written in Haskell)

### ISSUE THREAD

**Issue by webdevred** [BeamNG/vscode-jbeam-editor#15]
Hi! 👋  

I’m the main developer of [`jbeam_edit`](https://github.com/webdevred/jbeam_edit), a fast, robust command-line parser, formatter, and editor for JBeam files.  

It complements `vscode-jbeam-editor` by providing:  
- Consistent formatting
- Configurable formatting rules via my custom DSL, inspired by CSS

Example of how my DSL works:

```css
// Flexbodies usually contain nested data structures
.*.flexbodies[*] {
    NoComplexNewLine: true; /* compact formatting for flexbodies */
}
```

This piece configuration configures jbeam_edit to format this jbeam:

```json
{
  "example" : {
    "flexbodies" : [
      ["mesh", "[group]:", "nonFlexMaterials"],
      [
        "impala_fender_l",
        ["cot_fender_l"]
      ],
      [
        "impala_fender_inter_l",
        ["cot_fender_l"]
      ],
      [
        "impala_fender_r",
        ["cot_fender_r"]
      ],
      [
        "impala_fender_inter_r",
        ["cot_fender_r"]
      ]
    ]
  }
}
```
to be formatted  like this:
```json
{
  "example" : {
    "flexbodies" : [
      ["mesh", "[group]:", "nonFlexMaterials"],
      ["impala_fender_l", ["cot_fender_l"]],
      ["impala_fender_inter_l", ["cot_fender_l"]],
      ["impala_fender_r", ["cot_fender_r"]],
      ["impala_fender_inter_r", ["cot_fender_r"]]
    ]
  }
}
```

**Automatic vertex management (work in progress):**  
- Automatically moves vertices to their correct group (Left/Middle/Right)  
- Automatically sorts vertices according to their Y and Z values  
- Configurable X-value thresholds for defining Left/Middle/Right groups  
- Configurable Y-value thresholds to switch comparison to Z when differences are too small

I think a link to `jbeam_edit` could be useful for users who want a command-line tool or automated workflow for editing JBeam files. It would also help more people find the project, which in turn would provide more feedback for me on how to improve the software.  

Here’s the repo: [https://github.com/webdevred/jbeam_edit](https://github.com/webdevred/jbeam_edit)  

Would it be possible to add it to your README or a “Related Tools” section? I’d be happy to provide a short description if needed.  

Thanks for considering!

**Comment by angelo234** [comment]
Hey there,

So I tried out the tool to try and beautify a JBeam file, but unfortunately, it still seems to be WIP. I tried it out with a few JBeam files using the command `jbeam-edit jbeam_file.jbeam` and it messes up the formatting quite a bit. It also threw an error when I tried it out with a specific JBeam file (`vehicles\etk800\etk800_body_wagon.jbeam`) and failed to beautify it. The other JBeam files I tried it on were:
- `vehicles\autobello\autobello_body.jbeam` 
- `vehicles\ball\ball.jbeam`

Once these bugs have been fixed, I'd definitely consider adding it to the VSC JBeam Editor README page.

Best regards,
Angelo

**Comment by webdevred** [comment]
> Hey there,
> 
> So I tried out the tool to try and beautify a JBeam file, but unfortunately, it still seems to be WIP. I tried it out with a few JBeam files using the command `jbeam-edit jbeam_file.jbeam` and it messes up the formatting quite a bit. It also threw an error when I tried it out with a specific JBeam file (`vehicles\etk800\etk800_body_wagon.jbeam`) and failed to beautify it. The other JBeam files I tried it on were:
> 
>     * `vehicles\autobello\autobello_body.jbeam`
> 
>     * `vehicles\ball\ball.jbeam`
> 
> 
> Once these bugs have been fixed, I'd definitely consider adding it to the VSC JBeam Editor README page.
> 
> Best regards, Angelo

Hello Angelo,

Thanks for your feedback! I spent the weekend reviewing your report and identified a few issues that I’m currently addressing:

1. As you mentioned, `jbeam-edit` crashed when formatting `etk800_body_wagon.jbeam`. This was due to a bug in my parser: it didn’t expect comments before keys inside an object. This is fixed in master.
2. Certain structures that should stay on one line were expanded across multiple lines. This can be fixed using the NoComplexNewLine setting in the configuration file for those structures (e.g., `glowMap` and `variables`). The upcoming release will ship a default configuration file with this setting applied to the relevant structures.
3. Conversely, some structures that should be split over multiple lines ended up on a single line. I added a new setting, `ForceComplexNewLine`, to address this. I’m currently waiting for a teammate to update one of our example JBeam files so that our CI can verify that this new setting works. Once that’s done, I plan to release an updated version of jbeam-edit.
4. Some padding differed from the original files, particularly in `glowMap` in `autobello_body.jbeam`. Do you have any preferences regarding padding? This would help me ensure the formatting style meets your expectations. 

I would also like to mention that the part of jbeam-edit I consider a work in progress is the transformation functionality, which sorts and renames vertices. This functionality is turned off by default in the stable builds. If you provide more feedback, I aim to improve the quality of the formatter part of my jbeam-edit in the ways you prefer.

I really appreciate your detailed feedback and would be happy to receive any further suggestions.

Best regards,
August Johansson

**Edit:** Another problem that I noticed  was that my formatter added ".0" to integer numbers, that is also fixed in master.

**Comment by angelo234** [comment]
Hey August,

Sounds good, I look forward to seeing the fixes. Although there isn't a `glowMap` section in `autobello_body.jbeam`, maybe you are referring to a different file? About the transformation feature, I wouldn't recommend doing it. The listing of the nodes in most cases are already grouped together to define specific structures of the vehicle. Plus with renaming nodes, you'd have to rename all references of the node across all files in the specific vehicle folder.

Thanks,
Angelo

**Comment by webdevred** [comment]
Hi Angelo,

Thanks for the clarification, it seems I was mistakenly looking at a different file from autobello, which is why I thought there was a `glowMap` section in autobello_body.jbeam.

> About the transformation feature, I wouldn't recommend doing it. The listing of the nodes in most cases are already grouped together to define specific structures of the vehicle.

I understand your concern. The transformation system is actually one of the main reasons we started this project, so it’s something we want to support eventually. That said, it will remain disabled in stable builds so normal users won’t be affected by any instability.

> Plus with renaming nodes, you'd have to rename all references of the node across all files in the specific vehicle folder.

Yes, absolutely, that’s a requirement I’m aware of. The transformation code doesn’t handle cross-file updates yet, but I’m planning to implement that capability. It’s a significant step, so it will take some time to get right.

I look up forward to be able give you a update whenever we are to release a new release with the changes to the formatter.
Thanks again for taking the time to test the tool and share feedback. It really helps guide development in the right direction.

Best regards,
August

**Comment by webdevred** [comment]
Hi Angelo,

I wanted to give you a quick update since our last conversation.

A new version of jbeam-edit has now been released, version v0.0.5, and it includes several improvements based on the feedback you shared:
* The crash related to comments before object keys (which happened when formatting `etk800_body_wagon.jbeam`) has been fixed.
* Formatting behavior has been improved for structures that should stay on a single line or expand across multiple lines, thanks to the new `ForceComplexNewLine` option and updated configuration defaults.
* I have made changes to padding to decrease inconsistencies.
* Since BeamNG has a large modding community and preferred formatting rules can vary, I am not yet sure which default configuration rules to ship. Community input is essential for deciding which sections should have predefined formatting and how they should be configured. I have created a issue in our project, https://github.com/webdevred/jbeam_edit/issues/123. Users are welcome to provide their suggestions there.

As for the transformation system, it remains disabled in stable builds, but development is ongoing. Cross-file node renaming is still planned, though it will require careful implementation to avoid breaking references across files.

Thanks again for taking the time to test the tool and for providing such actionable feedback, it has genuinely improved the formatter.

If you encounter anything else or have further suggestions, I’d be happy to look into it.

---

**Edit:** I found another bug in my project, multi-line comments could end up being formatted weirdly. I fixed this yesterday evning, sadly it didnt get into the release. If you have more feedback, I would be happy to implement potential fixes and release a extra release with this those changes and this multiline comment fix. 

Example of multiline comment in our example file:

```
{
"chassis_rails":{
	"information":{
		"authors":"gittarrgy01",
		"name":"",
	},
	"slotType":"main",
/* The purpose of this file is prove that moving metadata along with vertices when
moving vertices works as intended.
See issue for #69 explanation on the transformation part of the codebase. */
//--Nodes--
```

Resulting formatted comment (with yesterdays fix):

```
{
  "chassis_rails" : {
    "information" : {"authors" : "gittarrgy01", "name" : ""},
    "slotType" : "main",
    /* The purpose of this file is prove that moving metadata along with vertices when
    moving vertices works as intended.
    See issue for #69 explanation on the transformation part of the codebase. */
    // --Nodes--
```

---

jbeam-edit v0.0.5: https://github.com/webdevred/jbeam_edit/releases/tag/v0.0.5
jbeam-edit v0.0.5 discussion: https://github.com/webdevred/jbeam_edit/discussions/125
My custom configuration language documentation: https://github.com/webdevred/jbeam_edit/blob/master/JBFL_DOCS.md
Minimal, default formatting configuration: https://github.com/webdevred/jbeam_edit/blob/master/examples/jbfl/complex.jbfl
Advanced formatting configuration: https://github.com/webdevred/jbeam_edit/blob/master/examples/jbfl/complex.jbfl

Best regards,
August

**Comment by webdevred** [comment]
Hello @angelo234,

I hope you are doing well.

Have you had a chance to look at my recent release of jbeam-edit?
I am planning to release a new version in the coming weeks with additional fixes, and I would greatly appreciate any feedback you might have. Your input will help me prioritize improvements and make the next release as useful as possible.

Thank you again for your time and support!

Best regards,
August

**Comment by angelo234** [comment]
Hi August,

Sorry for late reply, was busy with things. So I tried it out again, but I still see the same issues as last time with the strange and inconsistent formatting. Here's some examples from `vehicles\autobello\autobello_body.jbeam`:

<img width="632" height="667" alt="Image" src="https://github.com/user-attachments/assets/af009ae4-bcdf-4783-89f1-0fa48c627384" />
<img width="670" height="663" alt="Image" src="https://github.com/user-attachments/assets/c5dddfe9-d915-482b-8823-97dbc6184d5d" />
<img width="907" height="667" alt="Image" src="https://github.com/user-attachments/assets/938a6fcd-0d28-43ce-aaf0-1961dd1fffb6" />

Please pay attention to how the jbeam files are normally formatted.

Thanks,
Angelo

**Comment by webdevred** [comment]
Hi @angelo234,

Thanks for taking the time to test jbeam-edit again.

From the examples you shared, it looks like the formatter was still using an older configuration file. jbeam-edit automatically creates a config file if none exists, so updates to the default config do not overwrite existing ones. Because of that, the new formatting rules in v0.0.5, which should fix the problems we had, were not applied when you updated jbeam-edit. Apologies, I forgot to mention this.

To make testing easier, here is the updated recommended configuration:

```css
.*.nodes[*][*] {
    // Force 3 decimals (e.g., 1.000)
    PadDecimals: 3;
}

// Keep things inline where applicable (no extra newlines for nested content)
.*.nodes[*], .*.flexbodies[*],
.*.beams[*], .*.triangles[*],
.*.variables[*], .*.glowMap.*,
.*.rails.*, .*.props[*] {
    NoComplexNewLine : true;
}

.*.sounds {
    ForceComplexNewLine: true;
}

.*.glowMap.signal_L, .*.glowMap.signal_R,
.*.glowMap.checkengine, .*.glowMap.hazard,
.*.glowMap.battery,  .*.glowMap.highbeam,
.*.glowMap.parkingbrake, .*.glowMap.lowfuel,
.*.glowMap.lowpressure, .*.glowMap.abs {
    PadAmount : 20;
}

.*.glowMap.*.off .*.glowMap.*.on {
    PadAmount : 10;
}
```

You can find the configuration file in the jbeam_edit folder under your AppData directory. On Windows, the path is typically:

`C:\Users\<YourUsername>\AppData\Roaming\jbeam_edit\rules.jbfl`


For context, I focus on developing the JBeam formatting and transformation logic, while a teammate maintains the JBeam example set and verifies that the output matches common BeamNG formatting conventions. He has practical JBeam modding experience, but has been busy recently, so we haven’t been able to review formatting details together as often as we’d like. With more frequent internal review meetings, we likely would have caught the need to update the config after upgrading to a new version sooner.

JBFL is my custom DSL for customizing JBeam formatting when using jbeam-edit. I recommend reviewing the [JBFL documentation](https://github.com/webdevred/jbeam_edit/blob/master/JBFL_DOCS.md) in addition to the recommended JBFL snippet above to better understand how properties like `PadDecimals`, `NoComplexNewLine,` and `ForceComplexNewLine` work in practice.

If we can arrive at a set of formatting rules that works correctly for your JBeam files, I will ship those as built-in defaults to be loaded by default, even if they do not exist in the AppData config file. That way, the formatter will always load a correct baseline configuration, even if the user’s AppData config file is outdated, while still allowing users to customize formatting behaviour.

If anything still looks off when using the updated config, feel free to send more examples.

Best regards,
August

**Comment by angelo234** [comment]
Ah I see, ok I modified the config file accordingly and tried it again and the results look better. Although theres still some issues. For example with the slots section:
<img width="704" height="584" alt="Image" src="https://github.com/user-attachments/assets/8f65ef4c-56a7-439a-a65c-a48c861c7e4b" />

Also for most jbeam sections' arrays, the arguments in a single column should be aligned neatly like how most jbeam files are formatted, especially the nodes section. For example:
Instead of:
```
["w1rr", -0.640, -0.630, 0.660],
["w1r", -0.350, -0.760, 0.680],
["w1l", 0.350, -0.760, 0.680],
["w1ll", 0.640, -0.630, 0.660],
```
Should be:
```
["w1rr", -0.64, -0.63, 0.66],
["w1r",  -0.35, -0.76, 0.68],
["w1l",   0.35, -0.76, 0.68],
["w1ll",  0.64, -0.63, 0.66],
```

But yeah keep looking at the jbeam files for examples on how to format things, and also maybe it'd be better to get feedback from the community, like on the forums, since I'm kinda busy these days, sorry. Once you feel it's in good shape, you can let me know then about adding it to the README :)

Thanks,
Angelo

**Comment by webdevred** [comment]
Hello,
I am sorry about the problems, I am sorry that I taken your time. I always aim to improve the formatter, I will continue to talk to the community and try jbeam-edit on different files during the winter. I created a pull request in jbeam-edit which fixes the problem where jbeam-edit wouldnt read the the shipped config file, but only read the AppData config file.
Regarding nodes padding and the slots problems, this is the config that we will ship to fix them. jbeam-edit can already do padding as given in your example, given that it is configured to do so. The goal is to deliver a default configuration where padding is applied where applicable.

```css
// START: added things for padding nodes

.*.nodes[0][*] {
    PadAmount: 0; 
}

.*.nodes[*][*] {
    PadDecimals: 3;
    PadAmount: 6;  
}

.*.nodes[*][0] {
    PadAmount: 8;
    // Wider for typical vertex IDs
}
// END: added things for padding nodes

// Keep things inline where applicable (no extra newlines for nested content)
// FIX: Added slots here to fix the newlines problem in slots   
.*.nodes[*], .*.flexbodies[*],
.*.beams[*], .*.triangles[*],
.*.variables[*], .*.glowMap.*,
.*.rails.*, .*.props[*],
.*.slots[*] {
    NoComplexNewLine : true;
}

// skipping the rest of config file for brevity, the is rest is same as the config I sent in my previous message
```

Thanks for your patience, I will reach back whenever I have tried jbeam-edit on more files and talked to the community more.

Best regards,
August
